### PR TITLE
Multiple audio streams

### PR DESCRIPTION
**Pull request by lukasf**
The title says it all. Multi audio stream support. Also added stream info classes for inspecing streams, codecs, etc.

### CODE REVIEW

**Comment by mcosmin222** [comment]
Sadly I do not have any multiple audio stream files yet - I guess I can create them with audacity. I would also need to enable this feature in my app's UI.

But testing with single audio streams, there seem to be no breaking changes.

**Comment by mcosmin222** [comment]
To answer your question, yes, I do think we need backwards compatibility, just in case -> make the old AudioStream and VideoStream descriptors return the first stream in the array. These properties should then be marked as obsolete. Perhaps there are people who really did use them.

**Comment by lukasf** [comment]
It depends on what we want to do with this lib. If we want to merge it back at some point, I agree that we should keep them. If we continue to keep this separated, we could also decide to delete all the old junk. But since it is not much work to keep the old methods running, maybe it is best to just deprecate them for now.

**Comment by lukasf** [comment]
One problem is that the stream name and language are not shown in the MediaElement stream selection UI. All streams come as "unknown", even if I set name and language on the MediaStreamDescriptor. I have asked for help in the msdn forums, but I guess it is a bug. Maybe those properties are only used when actually encoding a file (where same descriptor classes are used), but not for playback, which would be sad.

That is the reason why I added the StreamInfo classes. So you can query the stream details form FFmpegInterop, to fill your custom stream selection UI. Or if you create MediaPlaybackItems from the MSS, you can also set name and language on the MediaPlaybackItem once it is opened, to get correct display in the default UI.

**Comment by mcosmin222** [comment]
I think they display the right names when you create the MediaPlaybackItem from other sources (like IRandomAccessStream). This works on their samples for MediaElement, but none of them use MediaStreamSource.

I think it is best to use the StreamInfo classes regardless, because we can expand them in the future and add Properties as needed and make richer custom UIs. 

We can't use the MediaPlaybackItem work-around, because it does not support all the formats FFMPEG supports.

**Comment by mcosmin222** [comment]
I think it would be useful to know which is the selected AudioStreamInfo. Same for SubtitleInfo

**Comment by MouriNaruto** [comment]
https://docs.microsoft.com/en-us/uwp/api/windows.media.core.mediastreamsource#Windows_Media_Core_MediaStreamSource_MaxSupportedPlaybackRate

`mss->MaxSupportedPlaybackRate = config->MaxSupportedPlaybackRate;`
Need Windows 10 RS2 or later.

**Comment by mcosmin222** [comment]
Any windows 10 before creators update is kind of meh. You don't even get the in-process background media, nor background video and multiple audio/video tracks. I am not sure if we should even bother with that.

**Comment by mcosmin222** [comment]
@lukasf, i wasnt referring to using the server mode overselves, but rather to use the same technique - win2D - to insert the subtitle when creating the video sample in ffmpeg.

**Comment by MouriNaruto** [comment]
A version check should be added because FFmpegInterop still support old Windows version.  @mcosmin222

**Comment by lukasf** [comment]
@MouriNaruto You are right, as long as the min platform of FFmpegInterop is set to 10240, we need to guard any calls to higher version APIs with a ApiInformation check. But even is we add that check, you'd still need to use the SDK that is used as Max Version.

Does anyone know an API analyzer that works with C++/Cx, to automatically report where we have unchecked API calls? I am not even sure if we are really compatible with 10240.

**Comment by lukasf** [comment]
@mcosmin222: Thing is, Win2D works on GPU surfaces, but MediaStreamSample only accepts IBuffer samples, not surfaces unfortunately. So we would have to copy the decoded image to GPU, apply subtitles with Win2D, then copy back to RAM, pass as IBuffer, then MF would later copy the image into GPU memory again to render it. So three copy operations instead of one. This is going to be very bad for performance, especially with 4K files. 

The only way to do this in a performant way (without platform rendering) would probably be to draw the subtitles on top of the MediaElement (either with XAML or Composition), where both would be rendered on GPU. Or maybe with FrameServer mode and Composition APIs - but I don't know how that is performance wise.

**Comment by mcosmin222** [comment]
Btw, there is a bug: I can't push a fix for some reason, but here's the correct method

```

void FFmpegInteropMSS::OnSwitchStreamsRequested(MediaStreamSource ^ sender, MediaStreamSourceSwitchStreamsRequestedEventArgs ^ args)
{
	mutexGuard.lock();
	if (currentAudioStream && args->Request->OldStreamDescriptor == currentAudioStream->StreamDescriptor)
	{
		if (currentAudioEffects)
		{
			currentAudioStream->DisableFilters();
		}
		currentAudioStream->DisableStream();
		currentAudioStream = nullptr;
	}
	for each (auto stream in audioStreams)
	{
		if (stream->StreamDescriptor == args->Request->NewStreamDescriptor)
		{
			currentAudioStream = stream;
			currentAudioStream->EnableStream();
			if (currentAudioEffects)
				currentAudioStream->SetFilters(currentAudioEffects);
		}
	}
	mutexGuard.unlock();
}
```
you forgot a null check before setting filters.

**Comment by mcosmin222** [comment]
@lukasf 
10240 and 10586 should be deprecated platforms. They are basically the same as windows phone 8.1. I do not believe we need to worry about them too much. I don't even think this repo was around before Creators update.

On top of that, I am not even sure how multiple streams would work on these platforms. They do not provide a programatic way of changing streams.

**Comment by lukasf** [comment]
Thanks for the bugfix. I checked it in but I also can't push right now. I had that problem yesterday already, after updating github VS plugin it started working again, but now I get errors again (something about user name).

I found out that MediaElement already has AudioStreamIndex since 10240. So while I do not care about that platform, I do not see a need to remove it.

**Comment by mcosmin222** [comment]
MediaElement yes, but MediaPlayer no.

**Comment by lukasf** [comment]
MediaPlayer was only added later, together with MediaPlaybackItem.

**Comment by mcosmin222** [comment]
Nah, MediaPlayer was added in 8.1, but only as a singleton with BackgroundMediaPlayer.Current.  And in Creators they promoted MediaPlayer to have the same functionality as the MediaElement.

**Comment by lukasf** [comment]
Oh that was the same class? I was not aware of that.

**Comment by mcosmin222** [comment]
Looks good for the great merge.

**Pull request merged**
