### PR TITLE
Add hevc main10 support

### PR DESCRIPTION
**Pull request by Tlaster**
HEVC Main 10 seems cannot work properly without installing [HEVC Video Extensions](https://www.microsoft.com/en-us/p/hevc-video-extensions/9nmzlz57r3t7)

### CODE REVIEW

**Comment by mcosmin222** [comment]
Hi,

Thanks for your contribution.
Can you provide a small sample file so we can test this? It needs only be like 30 seconds long or something.

**Comment by Tlaster** [comment]
[Sample video.zip](https://github.com/lukasf/FFmpegInterop/files/2811606/Sample.video.zip)
Here is a sample video and you can test it.

**Comment by mcosmin222** [comment]
Thanks. I shall test it when I get back from work, that is about 8 hours from now.

**Comment by mcosmin222** [comment]
This is not really needed, but could still be merged.. If you set PassthroughVideoHEVC in ffmpeginterop config, it will play.


This could be useful if we want to provide more granular setup for passthroughs. But it is up to @lukasf  to decide. If we do merge it, I think that IF needs to be broken into more granular conditions first.

**Comment by Tlaster** [comment]
I agree, it's better to break into more granular conditions first.

**Comment by lukasf** [comment]
Hi there, I was busy last week.

The reason why I added the profile check for H264 is that 10bit profiles for H264 are not supported by the vast majority of hardware decoders (or even all of them). 10bit was more like an experiment, even software decoders took quite some time to pick it up. But it turned out that it is quite useful, not only for animated content but even normal movies (depending on image kind / grain). So for HEVC it was included right from the start, and I believe all hardware decoders do support it (I might be wrong though). That is why I still think that we do not need an additional switch here - unless someone finds a HEVC hardware decoder that supports 8bit but not 10bit.

I agree that it would be useful to have fine-granular control over passthrough. 10bit is not the only thing that can make or break hardware acceleration. There are other things such as max bitrate, number of ref frames, specific encoder options. But right now I don't have an idea how we can make an interface for all this. We cannot add every single encoder option. Maybe we can add a callback that will be called from FFmpegInterop with some of the parameters, and will return the result of the check?

One other approach would be to just enable hardware acceleration, check if we get video output in the app, and switch back to software decoding if needed. This would need to be in the app code, of course. Not sure where we can detect this though. Maybe MediaPlaybackSession, or some event? While it is not very clean, it would catch all problems, even ones that cannot be known from encoding parameters (or ones that depend on parameters that are not known in FFmpegInterop during decoding).

**Comment by mcosmin222** [comment]
AFAIK, there is no event that would tell you if the sample you provide is playable or not. And even if it were, you'd need to recreate the media stream source .... Complicated.

However, the native windows application does know it cannot play it, so a way to detect does exist...

Maybe DirectX or some lower level MF API can retrieve the capabilities of graphics hardware...

**Comment by lukasf** [comment]
It is possible to enumerate hardware decoders and check for general format support (H264, HEVC). But it looks like it is not possible to get details on supported profile, level, ref frames. At least, I have not found a way to get this, and also DXVA Checker does not show it (and it shows a lot).

But I see that AVCodecContext has profile and level. Maybe we could add MaxProfile and MaxLevel properties for each passthrough format. This would allow more fine granular decision on whether to passthrough or not. For example, H264 hardware decoders usually only support Main Profile with Level 4.1, but currently we do not check the levels, which could result in broken images for Main@L4.2 or Main@L5.1. Then we could deprecate the old "Hi10P" property in favor of the new ones.

**Comment by mcosmin222** [comment]
@lukasf 
Should we still keep this PR open? We might indirectly fix this when we do auto detection of hardware acceleration.

**Comment by lukasf** [comment]
If I understand correctly, the PC of @Tlaster is only able to hardware devcode HEVC Main files, but not HEVC Main10 files.

@Tlaster Can you confirm this?

If we want to keep the old system in place (in case user disables auto detection), then it would make sense to include this HEVCMain10 property.

In fact, there are two HEVC hardware decoding profiles defined in DXVA2, one for HEVC Main and one for HEVC Main10. So there is a separate profile for it, and there might be hardware which only supports the Main profile but not the Main10. Given those facts, it makes sense to have separate HEVC switches for both Main and Main10.

In contrast, for H264 there is only one hardware acceleration profile, which is for H264 Main profile. There is no known hardware out there which does H264 Main10 and there is also no profile for it in DXVA2. So for H264 that Main10 property does not even make sense, we should have just always disabled passthrough for that. Only for HEVC the switch makes sense.

The only question is, do we add a bool property for it, or do we add a more elaborate system, to allow checking of both profile and level. The level check would be useful even for auto detection, because auto detection does not give us the supported levels.

**Comment by Tlaster** [comment]
@lukasf Kind of, it seems that Microsoft moves the hole HEVC hardware decoding support to a separate plugin which is 0.99$ at Windows store, I can not play both HEVC Main files and HEVC Main10 files, after installing the plugin everything works just fine.
Feel free to close the PR if it is not necessary.

**Comment by lukasf** [comment]
The "HEVC Video Extension" is a software decoder for HEVC. Since FFmpegInterop can also software decode HEVC (if you set passthrough to false), the extension is not really needed when using our library.

I will close this PR for now. I still do think that we need better manual controls. But we should first focus on proper auto detection. When we have a good concept for that, we can also improve manual controls, in a way that fits the auto detection concept.

**Pull request closed without merging**
