### PR TITLE
Update readme

### PR DESCRIPTION
**Pull request by lukasf**
I have been updating the readme.md file. A lot of stuff in there was wrong or outdated. Is anything missing?

Also I have thought about renaming our fork. A distinct name would make it more obvious that this really is a different and much improved version. Quite a lot of things I wrote in the readme.md are only true for our fork, not for the original version. Havig a separate name would make things more clear. Maybe something like FFmpegInterop-Adv. We could also choose a completely new name, like FFmpegUwp, but then we'd have to rename namespaces and classes as well, which is probably not such a good idea.

What do you think?

### CODE REVIEW

**Comment by lukasf** [comment]
You can check the new readme directly in github: Go to the repo main page, select the update-readme branch and then scroll down.

**Comment by mcosmin222** [comment]
I don't think we are the "windows OSS team".

You can also create ffmpeginterop object from streams at given URI.

**Comment by lukasf** [comment]
I think you forgot to switch the branch.

**Comment by lukasf** [comment]
This is not on master yet. See my second comment.

**Comment by mcosmin222** [comment]
Oh yeah. Sorry. looks good.

**Comment by MouriNaruto** [comment]
Tip: I think it is better to mention the FFmpegUniversal branch.

I also think we need to create a new repo if we don't want to pull request to Microsoft any more. 

Mouri.

**Comment by lukasf** [comment]
Yes, creating a separate repo (not a fork) would also help with those misguided pull requests. I googled a while ago if the default PR target for a fork can be changd. Responses were that a fork is intended for contributing changes back to the original project (for people who cannot directly contribute to that project). That is why PRs in a fork always go back to upstream master, and this cannot be chaged. If multiple people work on a fork, only delivering to that fork, then something is wrong. It should be a separate (cloned) git repository, not a fork.

I mean, logically it still is a fork, but we should not use a git fork to host it.

**Comment by mcosmin222** [comment]
So do we abandon ever going back to Microsoft repo?

**Comment by lukasf** [comment]
Starting with a completely separate repo does not mean that it is impossible to merge back. We'd just have to make sure that the complete history is maintained. So not just copy the current files over and check it, but instead merge the complete history into the new repo. I am pretty sure that git then allows us to cross-merge back to the original repo, using manual git commands.

But frankly, I don't believe that a merge-back is ever going to happen. I tried to shake up the project a year ago, creating lots of PRs with improvements and fixes. But as you know, not a single of those PRs got merged. Still all open, no activity. That project is pretty dead right now, unfortunately. The repo admin is also head of the Windows developer group, he is probably just way too busy to maintain FFmpegInterop. According to the docs, it was also never really ment to be a real active library community project. It was more intended to be a sample, to show how this could be done.

**Comment by lukasf** [comment]
It looks like it is possible to remove the "fork status" of an existing repository, turning it into a standalone, detached repo. This way, complete history will be preserved, including issues and PRs. Additionally, the repo can be renamed, to give it a more meaningful, unique name.

**Pull request merged**
