### PR TITLE
Organize files

### PR DESCRIPTION
**Pull request by lukasf**
The main project got a bit out-of-hand. I created a few subfolders (Effects, SampleProviders, Subtitles, Helpers) to make it easier to find the right file.

Should I go one step further and delete all that Windows 8 clutter? The file structure could be simplified a lot if we only keep Windows 10 files. I would maybe delete the JS sample as well. It is horrible to maintain and no one uses WinJS anyways.

### CODE REVIEW

**Comment by mcosmin222** [comment]
We can delete the winJS stuff.
We can keep the windows 10 and windows 8.1 project files in the same folder. We can make the "source" folder a subfolder of said folder.

We can keep only one solution.

**Comment by mcosmin222** [comment]
Afaik, the winJS isn't supported anymore officially.

**Comment by lukasf** [comment]
We have dropped Windows 8x support a while back, the Windows (Phone) 8 projects don't build since quite some time. I do not see a reason why we should keep those files when they don't work. It will only cause questions if people find and try them.

**Comment by mcosmin222** [comment]
Ok then. Then we keep only windows 10.

**Comment by lukasf** [comment]
Finished cleanup. Now we have a very simple file structure. Checkout the brach to see how things really look (diff is too hard to read).

**Comment by mcosmin222** [comment]
Looks good to me.

**Comment by lukasf** [comment]
Merged.

@mcosmin222 The current project file can be easily referenced directly from your app solution. I am pretty sure that it won't break your build anymore, give it a try. I changed it so it finds its dependencies, no matter where your other solution files and projects are.

**Comment by mcosmin222** [comment]
Cool. I will give it a try when I get the chance.

**Pull request merged**
