### PR TITLE
Optimize frame grabber + Embeded CC suport

### PR DESCRIPTION
**Pull request by mcosmin222**
Optimization for #24

### CODE REVIEW

**Comment by lukasf** [comment]
Surprisingly, the binary seek has turned out to be a LOT slower than normal seeking. I would have expected the opposite behavior. I think I will remove it again. It does not really make any sense if it is not faster...

**Comment by mcosmin222** [comment]
@lukasf I am getting the same results. Strange indeed.

**Comment by lukasf** [comment]
I removed binary seeking. It does not make any sense if it is not faster.
I also made VideoFrame disposable, so we can explicitly free the memory from C#.

**Comment by mcosmin222** [comment]
I am wondering if the get frame methods should be cancel-able.

**Comment by lukasf** [comment]
Good idea, this could make sense, especially when exactSeek=true. 
Latest commit should do the job.

From C#, you can cancel like this:

```
            var task = frameGrabber.ExtractVideoFrameAsync(TimeSpan.Zero);
            task.Cancel();
            await task;
```

**Comment by lukasf** [comment]
But of course you cannot cancel during frame decode...

**Comment by mcosmin222** [comment]
I was thinking of a different scenario, like having a request for one frame while the grabber is busy getting a previous request. It would prevent some unnecessary operations in situations such as the seekbar preview from where this all started, while also making it easier for the UI to keep track of runninh tasks.

**Comment by mcosmin222** [comment]
Looks good.

**Comment by mcosmin222** [comment]
@lukasf is there any particular reason why the VideoFrame destructor is empty? The fact that we call "Dispose" from C# does not automatically dispose the reference from the interop layer.

We should explicitly free the IBuffer reference.

**Comment by lukasf** [comment]
@mcosmin222  This is not an empty all, even if it looks like. When a WinRT class is destroyed, all ref fields are nulled as well, which will in turn call their destructors as well (if they are not referenced anymore). Unlike normal C++, you do not need to manually initialize or free ref fields.

**Comment by mcosmin222** [comment]
@lukasf I am not talking about the C++/CX side. The problem is when you project the destructor call as IDisposable in .net. They are not handled the same way, as the interop layer would still have a reference to your class even if you call Dispose, which will defer the ref count GC.

**Comment by lukasf** [comment]
@mcosmin222 As far as I know, a public C++/CX descructor is projected as Dispose() in C#, and calling Dispose in C# will call that destructor. A lot of WinRT classes use it, it would be very surprising if this does not work. It is true that the interop wrapper will hang around until the GC collects it. But since the underlying object has been deleted, this is not a problem (and it is not even possible to force collect it).

If you have other information from official side, please let me know.

**Comment by mcosmin222** [comment]
OK, you are right - I tested it. I was under the impression that it should behave the same way as XAML views.

**Comment by lukasf** [comment]
Xaml controls are not IDisposable, so yes, there it is up to the GC when they are really deleted from memory...

About the throttling: I think this is better done in the app or in a separate C# lib. C# just has so much better thread synchronization stuff (AsyncLock and friends, Rx). I would not want to do that in C++..

**Comment by mcosmin222** [comment]
The cancelation stuff is there to make the API easier to consume regardless of language, and since the exactSeek is an expensive operation it should support cancelation.  I just got the idea from brainstorming about the thumbnail previews.

Do you have some other functionality to add in the C# companion library? I do not see the point of doing it just for the seek previews, that is a pretty custom functionality.

**Comment by lukasf** [comment]
Then maybe I did not understand your post correctly. If you were only asking for cancellation of a frame request, then this is already possible now. The extract frame loop will check before each frame if cancellation is requested, and will throw if that is the case. This is what the interruption_point(); call does. IAsyncOperation can be cancelled from all languages.

After I checked the latest SDK, I am not so sure anymore if it will really support subtitles. There is the TimedMetadataStreamDescriptor, but there are no subtypes defined for subtitles, and no constructors. Subtitles also do not really work well with the MSS pull model, because there is not always a subtitle to show (and null sample means end of stream). For subtitles, a push model would be needed. So currently I assume that the TimedMetadataStreamDescriptor is only for encoding/transcoding - much like the Label and Language properties on StreamDescriptor, which do not work when used with MSS. So maybe subtitle support would be something that could be added in a separate library, and maybe in C#.

**Comment by mcosmin222** [comment]
@lukasf I will open a new issue for that.
This PR can be merged in the meantime ^^

**Comment by lukasf** [comment]
There was a small mistake in the frame position code. I kind of rounded the position, but acutally we want the frame that would be shown at that time, and not the next frame (even if it is closer).

I also added xml doc comments to FrameGrabber methods, just to try if this works. They do show up when using the lib, but unfortunately only in C++, not in C#. I don't know why. Anyways, I will leave them in. Maybe I can get this working at a later point.

**Comment by mcosmin222** [comment]
@lukasf good to merge.

**Pull request merged**
