### PR TITLE
Add support for ARM64

### PR DESCRIPTION
**Pull request by lukasf**
Now that VS2017.9 is out, we can support ARM64.

Downside is that ffmpeg build scripts will fail if VS2017 does not have the latest update.
Not sure if that is a problem.

### CODE REVIEW

**Comment by lukasf** [comment]
It's not like I believe that ARM64 platform is going to be very successful, still...

**Comment by MouriNaruto** [comment]
ARM64 binaries has been provided in FFmpegUniversal 4.0 and later. So you don't worry about the FFmpegUniversal branch.

**Comment by mcosmin222** [comment]
We shouldn't worry about VS versions, as they are readily available free of charge. There is no reason why someone shouldn't have the latest version.

Unless they work on an aircraft carrier or something, and they really need to compile ffmpeg.

**Comment by lukasf** [comment]
It's just that people would get a non descriptive build error on ffmpeg build.
Maybe a comment on that in the readme is sufficient.

VS 2017 15.9.x will do the job, VS2019 will build as well.

**Comment by lukasf** [comment]
Can someone test the build on their system? 
Would be good to get a second green light before merging. 

I ran App Cert Kit on my binaries and it showed no issues.

**Comment by mcosmin222** [comment]
I am building it right now.

**Comment by mcosmin222** [comment]
On a side note, it will take a while before I can do a store submission with ARM64 packages. I will need to create a new configuration.

**Comment by lukasf** [comment]
For me it's sufficient to know that the build script works. I assume that the rest will work as well. We don't have real devices to test this anyways. At least, I don't plan to buy one ;)

**Comment by mcosmin222** [comment]
Yeah but in order to submit an app to the store with ARM64, I need to create a new configuration for it in the solution. 

The bins checked out all good for me too. But sometimes the certification they do at the store submission is different than the local one.

**Comment by mcosmin222** [comment]
This has nothing to do with this project, but rather with consuming the DLLs inside other projects. 

**In order to compile your application for the ARM64 configuration, you must update your project's Minimum Version to the Windows 10 Fall Creators Update (Build 16299)**

This error is particularly annoying, because if you want to mix ARM64 with the rest of the bad boyz (x86, x64 and ARM), you are forced to target 16299 as minimum platform. Whereas the others can target lower versions, like 14393. 

This is a pretty major oversight from the compiler team.
I wonder how this can be solved without duplicating the project files.
I also wonder what are the market share of builds earlier than 16299.

**Comment by lukasf** [comment]
C++ projects can use lower SDK versions with ARM64. But C# and VB must use 16299 or higher. I guess most Windows 10 users are on that version already, since it's more than one year old. But on the other hand, the market share of ARM64 ist probably extremely small. I would not sacrifice users on older Win10 versions for those few ARM64 users, and taking the double work to support two platforms it probably not worth the effort yet, unless ARM64 gains a lot more traction.

But for new projects, I'd start with a recent SDK anyways, and then include ARM64...

**Comment by mcosmin222** [comment]
Yes, you are probably right. I think therr are just a handful (literally) of models using ARM64

**Comment by lukasf** [comment]
There might be potential if Qualcomm drastically reduces prices on their chips, or if they drastically improve performance. But putting up Qualcomms most expensive, high performance chips against Intels cheapest, low performance (Atom based) chips is not going to be successul. Battery life alone is not going to convince a lot of people to pay 800$ for a ARM64 device that has the same performance as a 300$ Intel device.

**Pull request merged**
