### PR TITLE
Update ffmpeg to v3.4.2

### PR DESCRIPTION
**Pull request by lukasf**
There were no breaking changes, no deprecations. I have done some testing, everything seems alright from what I see.

This includes the VS2017 build file. I hope I have done everything correctly with the submodule. If you open the changelog file in the ffmpeg folder, it should show 3.4.2 changes.

It would be great if you can do some testing as well. Let me know how it goes.

### CODE REVIEW

**Comment by lukasf** [comment]
What do you think about adding an ffmpeg version check? We can query the build version of ffmpeg, and throw if it does not meet a minimum build. It would be bad if people open issues, and later we find out they only had an outdated ffmpeg build. Since there were no breaking changes this time, we could set minimum version to 3.3.2.

We could also add an option to skip the version check in the config class. Then people have a workaound if they know what they are doing.

**Comment by mcosmin222** [comment]
I am fine with version checking.
I will update my ffmpeg too, and see how it works. This might take a while since I think I no longer have all the build tools installed.

**Comment by mcosmin222** [comment]
Did you manage to get the latest version to build? I keep getting linker errors, and no dlls are created.

**Comment by mcosmin222** [comment]
This only seems to be a problem with x86 and x64. ARM builds correctly. Strange...

**Comment by lukasf** [comment]
Did you perhaps run this from a VS dev cmd such as "ARM Cross Tools Command"? You must run run it from a "normal" cmd. Dev cmd sets some variables which will prevent "vsvarsall" from working correctly. Maybe I should add a check in the file, to error out early.

**Comment by lukasf** [comment]
I added checks to prevent this kind of problems. I also disabled encoders, devices and hwaccels in build configuration, to reduce code size a bit.

**Comment by mcosmin222** [comment]
I run it from power shell > CMD. Then I start the batch. I will try again the changes

**Comment by mcosmin222** [comment]
I cannot get the bat file to build on x86 and x64, and I've tried on 2 different PCs, so I will default to the manual builds.
Can you add the compilation guide for VS2017 (windows 10 and win7) to the official page?

https://trac.ffmpeg.org/wiki/CompilationGuide/WinRT#Windows10x86

**Comment by lukasf** [comment]
Are you trying to build ffmpeg "latest" or 3.4.2 as configured on this branch? Does building 3.3.2 work? The errors really sounds like an ffmpeg build problem. It is not a Windows function that cannot be linked.

**Comment by mcosmin222** [comment]
I have tried 3.4.2 and now I am trying the current snapshot from github.
Are you 100% sure 3.4.2 compiles fine for you on x86 and x64?

**Comment by lukasf** [comment]
Sure, I have compiled it multiple times now. I always clear Build folder before, so I know the assembly are new.

I'd recommend to maybe first try to build 3.3.2. You can copy the build files (2017 cmd plus config file) over from this branch.

Maybe there is also a git problem with the ffmpeg submodule.

**Comment by lukasf** [comment]
I just found out that you need to manually update the ffmpeg submodule. It is not updated automatically when you switch to the branch. Please switch to ffmpeg-342 branch. Then open GitBash in project root folder (e.g. FFmpegInterop-lukasf). Type:
```
git pull
git submodule update
```

Then to check you are on the right ffmpeg submodule branch, go to ffmpeg subfolder and check status:
```
cd ffmpeg
git status
```

It should show something like this:
```
lukas@YOGA720 MINGW64 /c/Source/FFmpegInterop-lukasf/ffmpeg ((n3.4.2))
$ git status
HEAD detached at 6a97ba5215
Untracked files:
  (use "git add <file>..." to include in what will be committed)

        .vs/
        Build - v3.3.2 VS2015/
        Build - v3.3.2 VS2017/
        Build/
        Build3.4.2/
        Output/

nothing added to commit but untracked files present (use "git add" to track)
```

There should be no differences. **"nothing added to commit but untracked files present (use "git add" to track)"** Untracked files should only be in build and output folders.

If you have changes, you can reset ffmpeg folder like this:
`git reset --hard`

This will reset all changes inside ffmpeg submodule. Your build output files will be left untouched. This only affects files tracked by git.

**Comment by mcosmin222** [comment]
I tried to manually build the latest snapshot from my C drive (the exact same setup used in the compilation guide linked above). It works.

I tried the same with the .bat file. It doesn't. The problem seems to be somewhere in the bat file and the config on my PC. Sadly, debugging these things is close to impossible.

**Comment by lukasf** [comment]
This is really strange... You are also running on Win10 x64 right?

[test.zip](https://github.com/lukasf/FFmpegInterop/files/1772660/test.zip)

I wrote a small test batch file which will output the build environment for all three target platforms (using "set" command). You can run it from the FFmpegInterop folder, press Ctrl+A, Ctrl+C to catch output and paste into a text file. My output is included so you can compare. Output contains first x86, then x64, then ARM. You can also send me your output if you want.


You could also prepare the environment as in ffmpeg manual guide for x86, then instead of running msys2 call "set". Now compare that output to what my test batch outputs for x86, check especially the MSYS2 folder, INCLUDE, LIB, LIBPATH.

**Comment by mcosmin222** [comment]
[mcosmin22_buildffmpeg_VS2017_test.txt](https://github.com/lukasf/FFmpegInterop/files/1772691/mcosmin22_buildffmpeg_VS2017_test.txt)

Yes, I am running windows 10 x64.

Aside from some file path differences, I also seem to inherit the env variables from VS2013 and 2015, and some other path configuration differences. But I am not sure if this is causes the issue.

**Comment by mcosmin222** [comment]
Back on topic, we are good with the latest ffmpeg.

**Comment by mcosmin222** [comment]
I think i know what the problem is. But it will take a bit to test my theory.

**Comment by mcosmin222** [comment]
So I reinstalled windows, for the simple reason VS2015 did not want to uninstall, so I said to start a clean state.

Now, the very same batch file gives up a different error for x86 and x64 builds:

nasm/yasm not found or too old. Use --disable-x86asm for a crippled build.

yasm is where it is supposed to be according to the instructions in the compilation guide.

**Comment by lukasf** [comment]
Huh strange. Sounds like it does not find yasm.exe Did you rename it to "yasm.exe" as per instruction? Did you try those "which X" commands to check MSYS finds all dependencies?

**Comment by mcosmin222** [comment]
Yes, they all check out ok.

image

**Comment by mcosmin222** [comment]
Seems the problem was in the YASM file itself, I was using the x64 one instead of the x32 one

**Comment by lukasf** [comment]
Oh, are you using a 32bit OS?

**Comment by mcosmin222** [comment]
no, the OS is x64

**Comment by lukasf** [comment]
Then the 64 bit version should be the right one.

**Comment by lukasf** [comment]
But according to the instructions, you can take either 64 or 32 bit, both can compile for both targets.

**Comment by mcosmin222** [comment]
Apparently not. It works now, with the x32 YASM, at least for x32 build anyway -> it created the binaries, no linker errors, so I guess YEY? 

I think this was one of the weird things like x32 process can't load an x64 exe, but everything in the chain is x64 according to my task manager. The only caveat is that my Visual Studio install is 32 bit.

My theory on the linker error was that VS2015 was interfering with VS2017 somehow. But after the YASM thingy, maybe it was YASM doing it the entire time.

**Comment by mcosmin222** [comment]
Feel free to merge this. and #17

**Comment by lukasf** [comment]
Merged

**Comment by touseefbsb** [comment]
@lukasf  can we have the updated method to build this repo and use it in our uwp projects in VS 2017 in the readme of this fork? or do we need to follow the old method for VS 2017? which we used to do in the original repo of ffmpeginterop? Thanks

**Comment by lukasf** [comment]
Hi @touseefbsb, I have updated the readme with VS2017 build instructions. If you have VS2015 installed as well, you should use the VS2015 files, as some people reported problems using VS2017 build files when also having VS2015 installed.

**Pull request merged**
