### PR TITLE
Add passthrough for VC1, WMV3, MPEG2 and VP9

### PR DESCRIPTION
**Pull request by lukasf**
Note: MPEG2 and VP9 require the following extensions for passthrough:

- MPEG-2 Video Extensions
- VP9 Video Extensions

Both are free. VP9 requires Windows 1809. I disabled passthrough for these codecs by default, they must be manually enabled. I think it is possible to check if the extensions are installed through UWP APIs, and automatically trigger installation if they are missing. But I never tried those Store APIs, so no promises.

### CODE REVIEW

**Comment by lukasf** [comment]
What is still missing here are switches in the sample apps. I felt that the UI gets overcrowded when I'd add 4 more switches. We might have to change the layout somehow. Or maybe we just don't show all the config items.

**Comment by mcosmin222** [comment]
Nice work!

Regarding the UI, i think we need granular passthroughs for audio and a single switch for video. We never use all the video passthroughs in a single instance since we only have one video stream.

**Comment by lukasf** [comment]
Good idea. One video passthrough switch would simplify the UI significantly.

**Comment by lukasf** [comment]
I updated the samples and added an SDK version check for VP9.

**Comment by mcosmin222** [comment]
I think we need to do some research on hardware support for these pass-throughs, and adjust the default values accordingly. For exmaple, HEVC should be "false" by default, as not a lot of hardware out in the wild supports it.

**Comment by lukasf** [comment]
I just checked in a class that helps detect if the required extensions are installed for MPEG2 and VP9 (and allows you to open store entry for them). 

Since checking for store entrys or hardware devices is expensive, I'd rather not do this automatically, each time a config class is created. It's probably better to leave this to the app, to call it once when appropriate, and fill passthrough themselves.

**Comment by lukasf** [comment]
About detecting hardware support: While there could be a better way, it definitely is possible to get hold of a ID3D11VideoDevice from a MediaStreamSource.

I asked about this on UserVoice (to see if custom DXVA hardware acceleration is theoretically possible):

https://wpdev.uservoice.com/forums/110705-universal-windows-platform/suggestions/31915711-mediastreamsource-add-way-to-use-imfgetservice-fr

I tested it and indeed I could get to the device instance. This is quite some time back, but the APIs are not that hard. From the device you can get the video service, there you enumerate the profiles. Profiles are well known GUIDs, such as "D3D11_DECODER_PROFILE_H264_VLD_NOFGT". So if you find that profile, you know that H264 hardware acceleration is available.

The downside is that I think you can get the device only once the MSS gets opened. So we should check if there are better ways to get access to a device in UWP. But as a fallback, it would be possible to create a fake MSS, open it with a MediaPlayer, do our checks as above and close it.

**Comment by mcosmin222** [comment]
We don't need to wait for mss, we can query that device at any time. I had some code samples somewhere to get the device at any time. It is like 3 lines of code.

**Comment by mcosmin222** [comment]
I don't think it is worth it to do it in our class. It should be the app that decide this.

**Comment by lukasf** [comment]
I actually got it working yesterday already. Will try to come up with some prototype implementation...

**Comment by lukasf** [comment]
I pushed a first implementation of hardware acceleration check, just to test things out. It is pretty fast, usually <20ms in release mode on my system. If we call it only once when first video is opened and cache values, it is probably a very good solution - much better than trying to manually select formats and having users complain if things don't work. We could also keep the Initialize method public, so it can be called by the app during startup (async, while other stuff is loaded). Then there would even be zero delay.

Not sure how to integrate it. We could add a property "AutoSelectVideoPassthrough" which is true by default. If set to false, it uses the old per-format properties. Or we use a enum VideoPassthroughMode { Auto, Manual, ForceSoftwareDecode, ForcePassthrough } where Manual meanse use the old properties and the last two options would force either software decode or passthrough for all formats.

**Comment by lukasf** [comment]
For reference, this is how VLC decides on HW acceleration. It is also good for knowing which profile levels are supported by a HW decoder.

https://github.com/videolan/vlc/blob/master/modules/codec/avcodec/directx_va.c

**Comment by lukasf** [comment]
Just thinking, maybe we should remove HW detection here and make a separate PR for that? HW detection is a complex topic and could take a longer time to get right. Better have the new passthrough formats on master already.

**Comment by mcosmin222** [comment]
Agreed. We should merge all the PRs we have active right now, and then we can approach this topic again.

**Comment by mcosmin222** [comment]
Regarding auto-detection: I think it could work. And would probably simplify the approach to passthroughs. Let's keep it simple with a bool "auto detect he support", rather than making it complicated with enums.

**Comment by lukasf** [comment]
I removed the codec checker stuff. Ready to merge?

**Comment by mcosmin222** [comment]
Yes.

**Comment by lukasf** [comment]
Done

**Pull request merged**
