### PR TITLE
ffmpeg 4.0 ABI changes

### PR DESCRIPTION
**Pull request by mcosmin222**
This PR contains the ABI compatibility changes for FFMPEG 4.0

### CODE REVIEW

**Comment by mcosmin222** [comment]
All the test files I have checked out OK, except for AVI files related to issue #44

**Comment by mcosmin222** [comment]
I cherry picked the fix for #44 to avoid possible future merge issues.

**Comment by lukasf** [comment]
@mcosmin222 ffmpeg 4.1 has been released few weeks back. Maybe now it is a good time to jump to the latest version. I updated the submodule and done a few smaller changes. For me it seems to work fine so far, I will try to do more testing in the next days...

By the way, do you use VS2015 or VS2017 build file? I use VS2017 all the time, it works really good for me.

**Comment by mcosmin222** [comment]
I honestly don't remember xD. It has been a very long time since I built it, but I think it was 2017. I will give it a try these days. 

Have you managed to test filters in the new version?

**Comment by lukasf** [comment]
I have not tested filters yet, will try to give them a shot in the next days.

**Comment by mcosmin222** [comment]
I think this branch needs to be rebased on master again, since there have been a few bug fixes since I created it.

**Comment by lukasf** [comment]
Good idea, better test with all bug fixes applied. Feel free to rebase, or I can also do it in the next days.

**Comment by lukasf** [comment]
Since rebasing is not possible (or dangerous) in git, I created a new branch and PR, which includes all master fixes. Please check #69. Closing this one.

**Pull request closed without merging**
