### PR TITLE
Integrate ffmpeg 4.1

### PR DESCRIPTION
**Pull request by lukasf**

### CODE REVIEW

**Comment by lukasf** [comment]
I have also created a branch legacy/ffmpeg-3.4, so people can still build against old ffmpeg version if they like. All legacy/* branches are automatically protected.

**Comment by MouriNaruto** [comment]
FFmpegUniversal has been updated yesterday.

https://github.com/M2Team/FFmpegUniversal/releases/tag/4.1

**Comment by touseefbsb** [comment]
@MouriNaruto  seems like ffmpegUniversal is doing exactly what ffmpeginterop does for uwp ? or is there a difference?

**Comment by MouriNaruto** [comment]
@touseefbsb FFmpegUniversal is a merged FFmpeg dynamic linked library for the Windows Universal Platform.
You can integrate FFmpegUniversal to FFmpegInterop.

Sample:
https://github.com/lukasf/FFmpegInterop/tree/FFmpegUniversal

**Comment by touseefbsb** [comment]
@MouriNaruto  what are benefits of using ffmpeguniversal with ffmpeginterop, instead of using ffmpeg with ffmpeginterop ?

**Comment by lukasf** [comment]
There are no functional benefits. But with FFmpegUniversal, you only need to reference and ship one ffmpeg dll, instead of 6 separate dlls. So file handling is a bit easier in the app where you use it. But FFmpegInterop needs quite a lot of changes when using it with the merged dll, so unfortunately, it is not easy to switch between original and FFmpegUniversal approach. There is a branch of FFmpegInterop which has the changes for FFmpegUniversal, but it is currently out of date.

I am not sure about the licensing implications of the dll merging used in FFmpegUniversal. ffmpeg consists of multiple libraries and it is usually licensed as lgpl (library gpl), which means that it must be possible for users to replace the shipped dlls with custom built dlls. I am not sure if the lgpl license even allows us to change the library structure. Even if it is allowed, we are then definitely forced to provide build tools and instructions to build such a merged dll, and we have to keep those hosted as long as our product is out. 

Personally, I prefer to just use the original ffmpeg dlls. Then I can just point to the official ffmpeg compilation guide. Everyone can replace the ffmpeg dlls with custom built ones or dlls from nuget or whatever, and does not even need to know about FFmpegUniversal. The file handling with FFmpegUniversal is a bit easier, but it's not such a big deal for me. For me, the benefits of sticking to original dll structure are more important.

**Comment by MouriNaruto** [comment]
> There is a branch of FFmpegInterop which has the changes for FFmpegUniversal, but it is currently out of date.
@lukasf I have updated that branch two days ago.

> I am not sure about the licensing implications of the dll merging used in FFmpegUniversal. ffmpeg consists of multiple libraries and it is usually licensed as lgpl (library gpl), which means that it must be possible for users to replace the shipped dlls with custom built dlls. 
@lukasf You can read the section 2 of LGPL (https://www.gnu.org/licenses/lgpl.html), and you will know if you modified a project which distributed under the LGPL, you need to distribute your modification under the LGPL or GPL. But FFmpegUniversal is a **independent** project or the **modified version** of FFmpeg, distributed under the same license as FFmpeg. For example, FFmpegUniversal uses LGPL 2.1 if you choose LGPL 2.1 to compile FFmpeg. Everyone can use FFmpegUniversal 's open source script to build FFmpeg and replace other one's FFmpegUniversal. So I think you don't need to worry about that.

**Comment by lukasf** [comment]
@MouriNaruto Thanks for the clarifications. And good to hear that the branch is up to date again.

It is just my personal preference to stay with the original dlls. Using FFmpegUniversal sure is an alternative, if simple file handling and deployment is important.

**Comment by mcosmin222** [comment]
Hi @lukasf 
It seems it works fine. I tested filters as well and they work properly.

**Comment by mcosmin222** [comment]
I also attached a profiler, which turned out no memory leaks.

**Comment by mcosmin222** [comment]
hi @lukasf 
I have added my review. Been using the library in a targeted fraction of my users (that's my non-dev devices + a few other people I know they use the player). It all checks out OK. 

Maybe @MouriNaruto  can throw a review as well, but from my part, we are good to merge.

**Comment by MouriNaruto** [comment]
@lukasf @mcosmin222 
I think we are good to merge. Hope it can bring us a better performance.

**Comment by lukasf** [comment]
I have also tested with a lot of files in the last days. I did not notice any issues.

What do you think about adding a version check for ffmpeg dll? This branch will only work with at least V4.0 of ffmpeg. Older versions will cause threading problems due to missing lock_manager.

**Comment by lukasf** [comment]
Maybe something like this? Check latest commit.

**Comment by lukasf** [comment]
It is opt-in, so dev can decide if he wants version checking, and which version to check for (minimum version, which is 4.0, or recommended version, which is 4.1 right now).

**Comment by lukasf** [comment]
Perhaps it should be moved to a separate class, to not clutter the main class interface.

**Comment by mcosmin222** [comment]
Sounds good. Maybe we should have a check in the build script as well? So this branch cannot compile 3.0 but will work for 4.0

**Comment by lukasf** [comment]
Then it would not be opt-in anymore. I'd rather let the build script build any version (and it is capable to build both 3.x and 4.x). And then there is also the fact that I don't know how to do partial string comparisons in build script ;)

**Comment by mcosmin222** [comment]
Maybe it shouldn't be an opt-in. We should do a one time check at process start to see if dlls match the version, otherwise throw exception. I don't see why you'd want the 3.0 branch using the 4.0 dll or the other way around.

We can expose the property in a class called ffmpeginfo or something if it needs to be consumed somewhere else.

**Comment by lukasf** [comment]
Maybe like this? Minimum version check is now mandatory (done when first using FFmpegInteropMss). Recommended version check is optional and must be called on FFmpegVersionInfo.

**Comment by mcosmin222** [comment]
Looks good. And maybe we can change the minimum check for each branch: the 3.0 checks minimum for 3.0, this one checks for 4.0

**Comment by lukasf** [comment]
I don't really plan to bring improvements to the 3.x branch. If you want to do it, feel free. But I'd only add this on master and use it for future versions.

**Comment by mcosmin222** [comment]
Ok. I will do it after the merge.

**Comment by lukasf** [comment]
Ok, merged!

**Comment by mcosmin222** [comment]
Nice, now we have 0 issues. xD

**Comment by lukasf** [comment]
Yes! :)

**Pull request merged**
